const bookRecipes = [
    {
        title: 'Spaghetti Carbonara',
        ingredients: [
            '12 ounces (about 340g) spaghetti',
            '2 large eggs',
            '1 cup (about 100g) grated Pecorino Romano cheese (or Parmesan)',
            '4 ounces (about 115g) pancetta or guanciale, diced',
            '2 cloves garlic, minced (optional)',
            'Freshly ground black pepper',
            'Salt to taste',
            'Fresh parsley, chopped (for garnish)',
        ],
        instructions: [
            'Cook the Pancetta:',
            'Boil the Pasta:',
            'Prepare the Sauce:',
            'Combine Pasta and Pancetta:',
            'Add the Egg Mixture:',
            'Serve:',
        ],
    },
    {
        title: 'Lasagna',
        ingredients: [
            '9 lasagna noodles',
            '1 pound ground beef',
            '1/2 cup chopped onion',
            '2 cloves garlic, minced',
            '1 can (15 ounces) tomato sauce',
            '1 can (6 ounces) tomato paste',
            '1 can (14 ounces) crushed tomatoes',
            '2 teaspoons sugar',
            '1 teaspoon dried basil',
            '1 teaspoon dried oregano',
            '1/2 teaspoon salt',
            '1/4 teaspoon black pepper',
            '15 ounces ricotta cheese',
            '1 egg',
            '3 cups shredded mozzarella cheese',
            '1 cup grated Parmesan cheese',
        ],
        instructions: [
            'Cook the lasagna noodles according to package directions.',
            'In a large skillet, cook ground beef, onion, and garlic over medium heat until meat is browned. Drain excess fat.',
            'Stir in tomato sauce, tomato paste, crushed tomatoes, sugar, basil, oregano, salt, and black pepper. Simmer for 30 minutes, stirring occasionally.',
            'In a mixing bowl, combine ricotta cheese and egg.',
            'Preheat the oven to 375°F (190°C).',
            'In a 9x13-inch baking dish, layer noodles, meat sauce, ricotta mixture, mozzarella, and Parmesan. Repeat layers.',
            'Bake for 25-30 minutes until hot and bubbly. Let stand for a few minutes before serving.',
        ],
    },
    {
        title: 'Penne alla Vodka',
        ingredients: [
            '12 ounces penne pasta',
            '1 tablespoon olive oil',
            '1 small onion, finely chopped',
            '2 cloves garlic, minced',
            '1 can (28 ounces) crushed tomatoes',
            '1/4 cup vodka',
            '1 cup heavy cream',
            '1/4 teaspoon crushed red pepper flakes',
            'Salt and black pepper to taste',
            'Fresh basil leaves, for garnish',
            'Grated Parmesan cheese, for serving',
        ],
        instructions: [
            'Cook penne pasta according to package directions; drain and set aside.',
            'In a large skillet, heat olive oil over medium heat. Add chopped onion and cook until translucent.',
            'Add minced garlic and cook for about 1 minute until fragrant.',
            'Stir in crushed tomatoes and vodka. Simmer for about 10 minutes.',
            'Reduce heat to low and stir in heavy cream and crushed red pepper flakes. Season with salt and black pepper to taste.',
            'Simmer for a few more minutes until heated through.',
            'Serve the vodka sauce over cooked penne pasta, garnished with fresh basil leaves and grated Parmesan cheese.',
        ],
    },
    {
        title: 'Fettuccine Alfredo',
        ingredients: [
            '8 ounces fettuccine pasta',
            '1/2 cup unsalted butter',
            '1 cup heavy cream',
            '1 1/2 cups grated Parmesan cheese',
            'Salt and black pepper to taste',
            'Chopped fresh parsley, for garnish',
        ],
        instructions: [
            'Cook the fettuccine pasta according to package instructions; drain and set aside.',
            'In a large skillet, melt the butter over medium heat.',
            'Add the heavy cream and bring to a simmer, stirring constantly.',
            'Stir in grated Parmesan cheese, salt, and black pepper. Continue to cook and stir until the sauce is smooth and thickened.',
            'Toss the cooked fettuccine in the Alfredo sauce to coat.',
            'Garnish with chopped fresh parsley and more Parmesan cheese if desired.',
        ],
    },
    {
        title: 'Pesto Linguine',
        ingredients: [
            '8 ounces linguine or your choice of pasta',
            '2 cups fresh basil leaves',
            '2 cloves garlic',
            '1/2 cup pine nuts',
            '1/2 cup grated Parmesan cheese',
            '1/2 cup extra-virgin olive oil',
            'Salt and black pepper to taste',
        ],
        instructions: [
            'Cook the linguine or pasta of your choice according to package directions; drain and set aside.',
            'In a food processor, combine fresh basil, garlic, pine nuts, and grated Parmesan cheese. Pulse until finely chopped.',
            'With the food processor running, slowly drizzle in the olive oil until a smooth pesto sauce forms. Season with salt and black pepper to taste.',
            'Toss the cooked pasta with the pesto sauce until well coated.',
            'Serve with additional grated Parmesan cheese if desired.',
        ],
    },
];

export default bookRecipes